name: Release Charts
on:
  workflow_call:
    inputs:
      git-username:
        type: string
        required: false
        default: 'Actions Bot'
      git-email:
        type: string
        required: false
        default: 'no-reply@no-reply.users.github.com'
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: New version
        id: version
        uses: cvacoop/.github/actions/jx-release-version@master
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
      - name: update version
        run: echo $VERSION > VERSION
        env:
          VERSION: ${{ steps.version.outputs.version }}
      - name: add terraform docs
        run: |
          cd ./actions/
          npm install -g action-docs
          for entry in $(ls -d */) 
          do
            cd $entry
            action-docs --no-banner > README.md
            cd ../
          done
      - name: Create Release Tag
        uses: cvacoop/.github/actions/release-tag@master
        with:
          git-token: ${{ secrets.ACTIONS_TOKEN }}
          version: ${{ steps.version.outputs.version }}
      - name: Release
        run: |
          gh release create $VERSION --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}